import { RandomFox } from "@/components/RandomFox";
import type { NextPage } from "next";
import Head from "next/head";

const random = () => {
  const typedArray = new Uint8Array(1);
  const randomValue = crypto.getRandomValues(typedArray)[0];
  return randomValue / Math.pow(2, 8);
};

const getRandomValue = (limit: number) => {
  return Math.floor(random() * limit) + 1;
};

const Home: NextPage = () => {
  return (
    <div className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20 font-[family-name:var(--font-geist-sans)]">
      <Head>
        <title>Random Fox App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col gap-8 row-start-2 items-center sm:items-start">
        <RandomFox image={ `https://randomfox.ca/images/${getRandomValue(123)}.jpg` } />
      </main>
      <footer className="row-start-3 flex gap-6 flex-wrap items-center justify-center"></footer>
    </div>
  );
}

export default Home;
