import { LazyImage } from "@/components/LazyImage";
import type { NextPage } from "next";
import Head from "next/head";
import { MouseEventHandler, useEffect, useState } from "react";

const random = () => {
  const typedArray = new Uint8Array(1);
  const randomValue = crypto.getRandomValues(typedArray)[0];
  return randomValue / Math.pow(2, 8);
};

const getRandomValue = (limit: number) => {
  return Math.floor(random() * limit) + 1;
};

const generateUniqueId = (): string => {
  return Math.random().toString(36).substring(2, 11);
};

type ImageItem = { id: string, url: string, };

const Home: NextPage = () => {
  const [images, setImages] = useState<Array<ImageItem>>([]);

  useEffect(() => {
    const script = document.createElement("script");
    script.src = "https://plausible.io/js/plausible.js";
    script.async = true;
    script.defer = true;
    document.body.appendChild(script);
  }, []);

  const addNewFox: MouseEventHandler<HTMLButtonElement> = (event) => {
    event.preventDefault();
    const newItem: ImageItem = {
      id: generateUniqueId(),
      url: `https://randomfox.ca/images/${getRandomValue(123)}.jpg`
    };
    setImages([
      ...images,
      newItem
    ]);
  };

  return (
    <div className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20 font-[family-name:var(--font-geist-sans)]">
      <Head>
        <title>Random Fox App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col gap-8 row-start-2 items-center sm:items-start">
        <button onClick={addNewFox} >Add new Fox</button>
        {
          images.map(({ id, url }, index) => (
            <div key={id} className="p-4">
              <LazyImage 
                src={ url } 
                title="Random Fox"
                width="320" 
                height="auto" 
                className="mx-auto rounded-md bg-gray-300"
                onLazyLoad={(img) => {
                  console.log(`Image #${index + 1} cargada. Nodo:`, img);
                }}
              />
            </div>
          ))
        }
      </main>
      <footer className="row-start-3 flex gap-6 flex-wrap items-center justify-center"></footer>
    </div>
  );
}

export default Home;
